# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hank < Formula
  desc "A CLI utility that makes error messages digestible and easy to understand using local LLMs"
  homepage "https://github.com/dillondesilva/hank"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dillondesilva/hank/releases/download/v0.1.1/hank_Darwin_x86_64.tar.gz"
      sha256 "47ca417c8d5df41ec9017bd0d97f456418c2f4ef5efaebf3f6b334af35caa5fe"

      def install
        bin.install "hank"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dillondesilva/hank/releases/download/v0.1.1/hank_Darwin_arm64.tar.gz"
      sha256 "d76caa458b14f80833ffea2640c66f85dce30ba860097576014dc158848596a1"

      def install
        bin.install "hank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dillondesilva/hank/releases/download/v0.1.1/hank_Linux_x86_64.tar.gz"
      sha256 "0c98127da1672f94216ab9de7aafedfb76c9cf949b05dd23931546def24c3627"
      def install
        bin.install "hank"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dillondesilva/hank/releases/download/v0.1.1/hank_Linux_arm64.tar.gz"
      sha256 "459fd7d1657ac50c3e009b75ea8e04762db0acb4008cad3e6b26baddedb1d88a"
      def install
        bin.install "hank"
      end
    end
  end

  test do
    system "#{bin}/hank", "--version"
  end
end
