# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hank < Formula
  desc "A CLI utility that makes error messages digestible and easy to understand using local LLMs"
  homepage "https://github.com/dillondesilva/hank"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dillondesilva/hank/releases/download/v0.1.2/hank_Darwin_x86_64.tar.gz"
      sha256 "9d8b9aed5254f0b0f3f6c59fa577ae56ce5f10904ab3f671560c31a80cf18b69"

      def install
        bin.install "hank"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dillondesilva/hank/releases/download/v0.1.2/hank_Darwin_arm64.tar.gz"
      sha256 "f7354efec48cd39017d6d0962db2ecc4b42fb8891af97f40d8afdc07bd5b61cc"

      def install
        bin.install "hank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dillondesilva/hank/releases/download/v0.1.2/hank_Linux_x86_64.tar.gz"
      sha256 "5360ffd847537c4ac38a894b821f9b9b3438856968f44196adf4b2f250e0df5e"
      def install
        bin.install "hank"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dillondesilva/hank/releases/download/v0.1.2/hank_Linux_arm64.tar.gz"
      sha256 "190b1b0ac21e1687deabe7dc979317a21dfe0ff1f3793620b20b5acaf5ef1944"
      def install
        bin.install "hank"
      end
    end
  end

  test do
    system "#{bin}/hank", "--version"
  end
end
